apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
      name: mongo
    spec:
      containers:
        - name: mongo-container
          image: mongo:latest
          ports:
            - containerPort: 27017
          envFrom:
            - configMapRef:
                name: mongo-configmap
          volumeMounts:
            - name: mongo-volume
              mountPath: /data/db
      volumes:
        - name: mongo-volume
          persistentVolumeClaim:
            claimName: mongo-pvc
  selector:
    matchLabels:
      app: mongo
  serviceName: mongo